### ISSUE TITLE
Version range for libgmp

### ISSUE THREAD

**Issue by HaoZeke** [meolic/biddy#1]
Hi, as part of the (very delayed) review https://github.com/openjournals/joss-reviews/issues/1189..

Could you mention the current `libgmp` in use? With the newest on Archlinux (6.1.2) I am having some issues, I will be testing with bundled versions from Ubuntu (via docker) but would like the information to be reflected on the `README.md` if possible

**Comment by meolic** [comment]
I am using libgmp from Ubuntu repository (tested on all recent Ubuntu versions). 

> apt list libgmp*
libgmp10/bionic,now 2:6.1.2+dfsg-2 amd64 [installed]
libmp-dev/bionic,now 2:6.1.2+dfsg-2 amd64 [installed]
libgmpxx4ldbl/bionic,now 2:6.1.2+dfsg-2 amd64 [installed,automatic]

Robert

**Comment by HaoZeke** [comment]
Thanks
