### ISSUE TITLE
Contributor guidelines

### ISSUE THREAD

**Issue by HaoZeke** [meolic/biddy#2]
Hi, as per the checklist items for https://github.com/openjournals/joss-reviews/issues/1189, one of the requirements are that guidelines for contribution must be established.

This is doubly important for Biddy, since my understanding is that the git mirror is not where pull requests or patches should be sent. Please add some details on how patches are to be contributed (by email for example).

**Comment by meolic** [comment]
Thank you for this obserrvation. I have updated the documentation. It is now included on the first page that contributions are welcome via GitHub or via email.

**Comment by HaoZeke** [comment]
Excellent, I believe that wraps this up
